/**
 * Regression test for bug #3018.
 *
 * @jon-hendry: running `$gsd-discuss-phase 81` in Codex Default mode (where
 * `request_user_input` is rejected) caused the agent to pick "reasonable
 * defaults" and proceed straight into writing CONTEXT.md / DISCUSSION-LOG.md
 * checkpoints — without ever surfacing the questions to the user. The
 * generated Codex skill adapter explicitly told it to do that:
 *
 *   "When `request_user_input` is rejected (Execute mode), present a
 *    plain-text numbered list and pick a reasonable default."
 *
 * Discuss-mode is the wrong place for that fallback. The contract should be:
 * stop, render the questions as plain text, wait for the user's answer.
 * Defaults may only be picked when the user has authorized non-interactive
 * mode (--auto / --all) or has explicitly approved them.
 *
 * The fix updates getCodexSkillAdapterHeader's Execute-mode fallback prose.
 * The adapter header is generated by a pure function — tests assert on
 * structural content (split into sections, walk the section text) rather
 * than wholesale string snapshots.
 */

'use strict';

process.env.GSD_TEST_MODE = '1';

const { test, describe } = require('node:test');
const assert = require('node:assert/strict');
const path = require('node:path');

const INSTALL = require(path.join(__dirname, '..', 'bin', 'install.js'));
const { getCodexSkillAdapterHeader } = INSTALL;

/**
 * Extract the "Execute mode fallback" section text from the adapter header.
 * Returns null if the section is missing. Section runs from the
 * "Execute mode fallback:" label up to the next heading or </codex_skill_adapter> tag.
 */
function extractExecuteModeFallback(header) {
  const m = header.match(/Execute mode fallback:\s*\n([\s\S]*?)(?=\n##\s|\n<\/codex_skill_adapter>)/);
  return m ? m[1].trim() : null;
}

describe('bug #3018: codex skill adapter must not silently default discuss-phase decisions', () => {
  test('exported as a function', () => {
    assert.equal(typeof getCodexSkillAdapterHeader, 'function');
  });

  test('header still has an Execute mode fallback section (regression of existing #2760 test)', () => {
    const header = getCodexSkillAdapterHeader('gsd-discuss-phase');
    const fallback = extractExecuteModeFallback(header);
    assert.ok(fallback, `Execute mode fallback section must exist:\n${header}`);
    assert.ok(fallback.length > 0, 'fallback section must have content');
  });

  test('fallback instructs the agent to STOP and surface plain-text questions, not pick defaults', () => {
    const header = getCodexSkillAdapterHeader('gsd-discuss-phase');
    const fallback = extractExecuteModeFallback(header);
    // Behavioral invariant: the fallback must contain a stop-and-ask directive.
    // We assert on a small set of structural keywords that any correct prose
    // would contain ("stop"/"wait"/"plain text"), and explicitly forbid the
    // dangerous "pick a reasonable default" instruction that caused #3018.
    const lower = fallback.toLowerCase();
    assert.ok(/\b(stop|halt|wait)\b/.test(lower),
      `fallback must instruct the agent to STOP/WAIT, got:\n${fallback}`);
    assert.ok(/plain.?text|numbered list/.test(lower),
      `fallback must instruct presenting questions as plain text, got:\n${fallback}`);
    // Anti-pattern guard: the dangerous instruction must NOT appear.
    assert.ok(!/pick (a |the )?(reasonable|sensible|sane) default/i.test(fallback),
      `fallback must NOT instruct the agent to pick defaults autonomously (#3018), got:\n${fallback}`);
  });

  test('fallback names the conditions under which defaults ARE acceptable (--auto / --all / explicit approval)', () => {
    const header = getCodexSkillAdapterHeader('gsd-discuss-phase');
    const fallback = extractExecuteModeFallback(header);
    // The original report's expected behavior: defaults are OK only when the
    // user opted in non-interactively (--auto / --all) or has explicitly
    // approved. The fallback prose should name at least one of those paths
    // so the agent has a deterministic permission rule to follow.
    const lower = fallback.toLowerCase();
    const namesPermissionPath =
      /--auto|--all/.test(fallback) ||
      /explicit(ly)? (approv|authoriz|consent)/i.test(fallback) ||
      /user (has )?approv|user (has )?authoriz|user (has )?consent/i.test(fallback);
    assert.ok(namesPermissionPath,
      `fallback must name the permission paths under which defaults are allowed (--auto/--all or explicit approval), got:\n${fallback}`);
  });

  test('fallback explicitly forbids writing artifacts (CONTEXT.md / DISCUSSION-LOG.md / checkpoints) before the user answers', () => {
    const header = getCodexSkillAdapterHeader('gsd-discuss-phase');
    const fallback = extractExecuteModeFallback(header);
    // The reporter's specific symptom: the agent started writing
    // CONTEXT.md / DISCUSSION-LOG.md / checkpoint artifacts before any user
    // answer. The fallback must tell the agent not to do that.
    const lower = fallback.toLowerCase();
    const namesArtifacts = /artifact|checkpoint|context\.md|discussion.?log|do not write|don't write/i.test(fallback);
    assert.ok(namesArtifacts,
      `fallback must explicitly forbid writing artifacts before user answers (#3018), got:\n${fallback}`);
  });
});
