/**
 * @gsd/events - Shared event types for Socket.IO communication
 *
 * Event naming follows prefix:action pattern per CONTEXT.md:
 * - agent:* - Agent lifecycle events
 * - checkpoint:* - Checkpoint interaction events
 * - connection:* - Health/connection events
 */

// Prefixed event names per CONTEXT.md
export const EVENTS = {
  AGENT_TOKEN: 'agent:token',
  AGENT_START: 'agent:start',
  AGENT_END: 'agent:end',
  AGENT_ERROR: 'agent:error',
  CHECKPOINT_REQUEST: 'checkpoint:request',
  CHECKPOINT_RESPONSE: 'checkpoint:response',
  CONNECTION_HEALTH: 'connection:health',
} as const;

export type EventName = (typeof EVENTS)[keyof typeof EVENTS];

// Event payloads

/**
 * Token streaming event - sent for each token generated by the agent
 */
export interface TokenEvent {
  agentId: string;
  token: string;
  sequence: number;
}

/**
 * Agent start event - sent when an agent begins executing a task
 */
export interface AgentStartEvent {
  agentId: string;
  planId: string;
  taskName: string;
}

/**
 * Agent end event - sent when an agent completes (success, error, or checkpoint)
 */
export interface AgentEndEvent {
  agentId: string;
  status: 'success' | 'error' | 'checkpoint';
  summary?: string;
}

/**
 * Agent error event - sent when an agent encounters an error
 */
export interface AgentErrorEvent {
  agentId: string;
  code: string;
  message: string;
  recovery?: string;
  stack?: string;
}

/**
 * Checkpoint request event - sent when agent needs user input
 */
export interface CheckpointRequestEvent {
  checkpointId: string;
  type: 'human-verify' | 'decision' | 'human-action';
  prompt: string;
  options?: CheckpointOption[];
  timeoutMs?: number;
}

export interface CheckpointOption {
  id: string;
  label: string;
}

/**
 * Checkpoint response event - sent when user responds to a checkpoint
 */
export interface CheckpointResponseEvent {
  checkpointId: string;
  response: string;
}

/**
 * Connection health event - sent periodically for app-level health monitoring
 */
export interface ConnectionHealthEvent {
  timestamp: string;
  latencyMs: number;
}

// Socket.IO typed events

/**
 * Events emitted from server to client
 */
export interface ServerToClientEvents {
  [EVENTS.AGENT_TOKEN]: (event: TokenEvent) => void;
  [EVENTS.AGENT_START]: (event: AgentStartEvent) => void;
  [EVENTS.AGENT_END]: (event: AgentEndEvent) => void;
  [EVENTS.AGENT_ERROR]: (event: AgentErrorEvent) => void;
  [EVENTS.CHECKPOINT_REQUEST]: (event: CheckpointRequestEvent) => void;
  [EVENTS.CONNECTION_HEALTH]: (event: ConnectionHealthEvent) => void;
}

/**
 * Events emitted from client to server
 */
export interface ClientToServerEvents {
  [EVENTS.CHECKPOINT_RESPONSE]: (event: CheckpointResponseEvent) => void;
  'agent:subscribe': (agentId: string) => void;
  'agent:unsubscribe': (agentId: string) => void;
}

/**
 * Inter-server events (for future scaling)
 */
export interface InterServerEvents {
  ping: () => void;
}

/**
 * Socket data stored per connection
 */
export interface SocketData {
  projectId?: string;
  subscribedAgents: Set<string>;
}
